<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE properties [
<!ELEMENT properties ( comment?, entry* ) >
<!ATTLIST properties version CDATA #FIXED "1.0">
<!ELEMENT comment (#PCDATA) >
<!ELEMENT entry (#PCDATA) >
<!ATTLIST entry key CDATA #REQUIRED>
]>

<properties>
	<comment>Test data for RBCPTest.java</comment>
	
	<entry key="mainMenu.game">Game</entry>
	<entry key="mainMenu.game.declareIndependence">Declare Independence</entry>
	<entry key="mainMenu.game.newGame">New Free Play Game</entry>
	<entry key="mainMenu.game.exitGame">Exit Game</entry>
	<entry key="mainMenu.game.saveGame">Save Game</entry>
	<entry key="mainMenu.game.loadGame">Load Game</entry>
	<entry key="mainMenu.game.quitGame">Quit MicroCol</entry>

	<entry key="mainMenu.view">View</entry>
	<entry key="mainMenu.view.center">Center</entry>
	<entry key="mainMenu.view.europe">Evrope</entry>
	<entry key="mainMenu.view.turnReport">Turn report</entry>
	<entry key="mainMenu.view.statistics">Statistics</entry>
	<entry key="mainMenu.view.menuItemGoals">Mission Goals</entry>

	<entry key="mainMenu.unit">Unit</entry>
	<entry key="mainMenu.unit.move">Move</entry>
	<entry key="mainMenu.unit.buildColony">Build Colony</entry>
	<entry key="mainMenu.unit.nextUnit">Next unit</entry>
	<entry key="mainMenu.unit.plowFied">Plow field</entry>

	<entry key="mainMenu.preferences">Preferences</entry>
	<entry key="mainMenu.preferences.language">Language</entry>
	<entry key="mainMenu.preferences.language.cz">Czech</entry>
	<entry key="mainMenu.preferences.language.en">English</entry>
	<entry key="mainMenu.preferences.volume">Volume</entry>
	<entry key="mainMenu.preferences.animationSpeed">Animation speed</entry>
	<entry key="mainMenu.preferences.showGrid">Show Grid</entry>
	<entry key="mainMenu.preferences.showFightAdvisor">Use Fight Advisor</entry>

	<entry key="mainMenu.help">Help</entry>
	<entry key="mainMenu.help.about">About</entry>
	<entry key="mainMenu.help.colonizopedia">Colonizopedia</entry>

	<entry key="aboutDialog.caption">About MicroCol</entry>
	<entry key="nextTurnButton">Next turn</entry>
	<entry key="nextTurnButton.desctiption">Perform next turn, other players will move</entry>
	<entry key="tile.ocean.name">Ocean</entry>
	<entry key="tile.ocean.description">Wide ocean, where you can travel fast and safe</entry>

	<entry key="chooseGoodAmount.caption">How many would you like to transfer?</entry>
	<entry key="chooseGoodAmount.zero">Nothing</entry>
	<entry key="chooseGoodAmount.everything">Everything</entry>
	<entry key="chooseGoodAmount.selectedAmount">Selected amount: </entry>

	<entry key="europeDialog.caption">European Port</entry>
	
	<entry key="buyUnitDialog.title">Buy unit</entry>
	<entry key="buyUnitDialog.buttonBuyUnit">Buy for</entry>

	<entry key="recruitUnitDialog.title">Recruite unit</entry>
	<entry key="recruitUnitDialog.buttonRecruiteUnit">Pay</entry>

	<entry key="newGameDialog.title">New game</entry>
	<entry key="newGameDialog.selectMap">Select map</entry>
	<entry key="newGameDialog.cancel">Cancel</entry>
	<entry key="newGameDialog.startGame">Start play</entry>

	<entry key="europe.title">Europe</entry>
	<entry key="europe.shipsTravelingToNewWorld">Ships traveling to New World</entry>
	<entry key="europe.shipsTravelingToEurope">Ships traveling to Europe</entry>
	<entry key="europe.pier">Pier</entry>
	<entry key="europe.recruit">Recruit</entry>
	<entry key="europe.buy">Buy</entry>
	
</properties>