<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE properties [
<!ELEMENT properties ( comment?, entry* ) >
<!ATTLIST properties version CDATA #FIXED "1.0">
<!ELEMENT comment (#PCDATA) >
<!ELEMENT entry (#PCDATA) >
<!ATTLIST entry key CDATA #REQUIRED>
]>

<properties>
	<comment>Define keys for Europe dialog</comment>

	<entry key="title">Europe</entry>
	<entry key="shipsTravelingToNewWorld">Ships traveling to New World</entry>
	<entry key="shipsTravelingToEurope">Ships traveling to Europe</entry>
	<entry key="pier">Pier</entry>
	<entry key="recruit">Recruit</entry>
	<entry key="buy">Buy</entry>
	<entry key="buyUnitDialog_title">Buy unit</entry>
	<entry key="buyUnitDialog_buttonBuyUnit">Buy for</entry>
	<entry key="goodsPanelTitle">Goods</entry>
	<entry key="europePier">Pier</entry>
	<entry key="recruitUnitDialogTitle">Recruite unit</entry>
	<entry key="recruitUnitDialogButton">Pay</entry>
	<entry key="statusBarEuropeDock">Europe dock, ships could be loaded with goods and units.</entry>
	<entry key="statusBarShipsToNewWorld">Ships heading to New World</entry>
	<entry key="statusBarShipsToEurope">Ships heading to Europe</entry>
	<entry key="statusBarPier">Pier, there will be units waiting for travel to New World.</entry>
	<entry key="goodsToSell">Sell goods {0} for {1} gold or buy it for {2} gold.</entry>
	<entry key="buttonClose">Close Europe port. Return back to main world view.</entry>
	<entry key="buttonBuyUnit">Buy new unit.</entry>

</properties>